sudo: required
services:
  - docker

before_install:
  - docker build -t irsan238/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true irsan238/react-test npm test

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  - docker build -t multi-nginx ./nginx

  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  #Take image and push to docker hub
  - docker push multi-client
  - docker push multi-server
  - docker push multi-worker
  - docker push multi-nginx